// Auto-generated by directory-launcher scaffold_site.py
// Niche: Olietank verwijderen

export const nicheConfig = {
  // Identiteit
  slug: "olietank",
  naam: "Olietank verwijderen",
  naamMeervoud: "olietankverwijderaars",
  domein: "olietankverwijderen.nl",
  baseUrl: "https://olietankverwijderen.nl",

  // Branding
  siteNaam: "Olietankverwijderen.nl",
  tagline: "Vind gecertificeerde olietankverwijderaars",
  accentKleur: "#2563eb",

  // SEO
  titelHome: "Gecertificeerde Olietankverwijderaars in Nederland | Olietankverwijderen.nl",
  beschrijvingHome: "Vergelijk gecertificeerde olietankverwijderingsbedrijven in Nederland. Vraag gratis offertes aan en vind de beste specialist bij jou in de buurt.",
  hoofdKeyword: "olietank verwijderen",
  longTailKeywords: [
    "olietank verwijderen kosten",
    "olietank verwijderen [stad]",
    "olietank saneren",
    "ondergrondse olietank verwijderen",
    "olietank laten verwijderen"
  ],

  // Certificeringen
  certificeringen: [
    { code: "BRL-7000", naam: "BRL SIKB 7000 - Uitvoering van (water)bodemsaneringen" }
  ],

  // Specialisaties
  specialisaties: [
    { slug: "ondergronds", naam: "Ondergrondse tanks" },
    { slug: "bovengronds", naam: "Bovengrondse tanks" },
    { slug: "sanering", naam: "Bodemsanering na verwijdering" },
    { slug: "onderzoek", naam: "Bodemonderzoek" }
  ],
} as const;

export type NicheConfig = typeof nicheConfig;
